### ISSUE TITLE
should prune empty modules?

### ISSUE THREAD

**Issue by machty** [square/qunit-bdd#15]
Nested describe/context produces a bunch of intermediate module names, some which are entirely empty, e.g:

![](http://cl.ly/image/0g0P06152X1U/Image%202014-06-25%20at%203.42.19%20PM.png)

Ideally, selecting Sequence would set the `filter=Sequence` query param rather than `module=Sequence`, which won't match any child modules, and Sequence itself might be empty (since tests are only defined on sub describe/context). 

My guess is that QUnit-bdd only has so much control over this behavior, just wondering what our options were.

**Comment by eventualbuddha** [comment]
Closing as the project is deprecated.
